[font]
size = 11

[font.normal]
# family = "FiraMonoNerdFont"
# family = "GeistMonoNerdFont"
# family = "DaddyTimeMonoNerdFont"
# family = "FiraCodeNerdFont"
# family = "GohuFont11NerdFont"
family = "GoMonoNerdFont"

[window]
opacity = 0.75

[colors]
transparent_background_colors = true
