[font]
size = 10

[font.normal]
# family = "FiraMonoNerdFont"
# family = "GeistMonoNerdFont"
# family = "DaddyTimeMonoNerdFont"
# family = "FiraCodeNerdFont"
# family = "GohuFont11NerdFont"
family = "GoMonoNerdFont"

[window]
opacity = 0.9

[colors]
transparent_background_colors = true
