hotKey:
  pod:
    shortCut:    Shift-1
    description: Viewing pods
    command:     pods
  deployment:
    shortCut:    Shift-2
    description: View deployments
    command:     dp
  secret:
    shortCut:    Shift-3
    description: View secrets
    command:     secrets
  xray:
    shortCut:    Shift-4
    description: Xray Deployments
    command:     xray deploy
